"""SQLAlchemy domain models.

Each derived artifact in the system is traceable to its sources; the schema is
introduced incrementally, one bead at a time.
"""

from datetime import datetime
from typing import Any

from geoalchemy2 import Geometry
from geoalchemy2.elements import WKBElement
from sqlalchemy import (
    DateTime,
    Float,
    ForeignKey,
    Index,
    MetaData,
    String,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Areas of interest are stored in WGS 84 (EPSG:4326); loaders reproject on ingest.
AOI_SRID = 4326

# Deterministic constraint names keep hand-written and autogenerated migrations consistent.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for all Open Forest Sentinel models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Aoi(Base):
    """A configured area of interest: the geometry the pipeline runs against."""

    __tablename__ = "aoi"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String, nullable=False, unique=True)
    geometry: Mapped[WKBElement] = mapped_column(
        Geometry(geometry_type="MULTIPOLYGON", srid=AOI_SRID),
        nullable=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )


class Observation(Base):
    """One imagery acquisition over an AOI; the source record for derived artifacts."""

    __tablename__ = "observation"

    id: Mapped[int] = mapped_column(primary_key=True)
    aoi_id: Mapped[int] = mapped_column(
        ForeignKey("aoi.id", name="fk_observation_aoi_id_aoi"),
        nullable=False,
    )
    sensor: Mapped[str] = mapped_column(String, nullable=False)
    acquired_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    source_scene_id: Mapped[str] = mapped_column(String, nullable=False)
    cloud_cover_percent: Mapped[float | None] = mapped_column(Float, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    __table_args__ = (
        UniqueConstraint(
            "aoi_id",
            "source_scene_id",
            name="uq_observation_aoi_id_source_scene_id",
        ),
        Index("ix_observation_aoi_id_acquired_at", "aoi_id", "acquired_at"),
    )


class MethodologyVersion(Base):
    """A processing/detection method record; derived artifacts reference one of these."""

    __tablename__ = "methodology_version"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String, nullable=False)
    version: Mapped[str] = mapped_column(String, nullable=False)
    parameters: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    __table_args__ = (
        UniqueConstraint("name", "version", name="uq_methodology_version_name_version"),
    )


class IndexRaster(Base):
    """A computed index raster (NBR or NDVI) for one observation."""

    __tablename__ = "index_raster"

    id: Mapped[int] = mapped_column(primary_key=True)
    observation_id: Mapped[int] = mapped_column(
        ForeignKey("observation.id", name="fk_index_raster_observation_id_observation"),
        nullable=False,
    )
    methodology_version_id: Mapped[int] = mapped_column(
        ForeignKey("methodology_version.id", name="fk_index_raster_methodology_version_id"),
        nullable=False,
    )
    index_type: Mapped[str] = mapped_column(String, nullable=False)
    cog_path: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    __table_args__ = (
        UniqueConstraint(
            "observation_id",
            "index_type",
            "methodology_version_id",
            name="uq_index_raster_observation_index_methodology",
        ),
    )


class ChangeRaster(Base):
    """A ΔNBR or ΔNDVI raster for one observation: current minus trailing-median baseline."""

    __tablename__ = "change_raster"

    id: Mapped[int] = mapped_column(primary_key=True)
    observation_id: Mapped[int] = mapped_column(
        ForeignKey("observation.id", name="fk_change_raster_observation_id_observation"),
        nullable=False,
    )
    methodology_version_id: Mapped[int] = mapped_column(
        ForeignKey("methodology_version.id", name="fk_change_raster_methodology_version_id"),
        nullable=False,
    )
    change_type: Mapped[str] = mapped_column(String, nullable=False)
    cog_path: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    __table_args__ = (
        UniqueConstraint(
            "observation_id",
            "change_type",
            "methodology_version_id",
            name="uq_change_raster_observation_change_methodology",
        ),
    )


class ChangeRasterSource(Base):
    """Many-to-many provenance: which index_rasters contributed to a change_raster."""

    __tablename__ = "change_raster_source"

    change_raster_id: Mapped[int] = mapped_column(
        ForeignKey(
            "change_raster.id",
            name="fk_change_raster_source_cr_id",
            ondelete="CASCADE",
        ),
        primary_key=True,
    )
    index_raster_id: Mapped[int] = mapped_column(
        ForeignKey("index_raster.id", name="fk_change_raster_source_ir_id"),
        primary_key=True,
    )
